import { type Theme } from 'json-edit-react'

export const githubDarkTheme: Theme = {
  displayName: 'Github Dark',
  styles: {
    container: {
      backgroundColor: '#0d1117',
      color: 'white',
    },
    dropZone: 'rgba(165, 214, 255, 0.17)',
    property: '#E6EDF3',
    bracket: '#56d364',
    itemCount: '#8B949E',
    string: '#A5D6FF',
    number: '#D2A8FF',
    boolean: { color: '#FF7B72', fontSize: '90%', fontWeight: 'bold' },
    null: 'green',
    iconCollection: '#D2A8FF',
    iconEdit: '#D2A8FF',
    iconDelete: 'rgb(203, 75, 22)',
    iconAdd: 'rgb(203, 75, 22)',
    iconCopy: '#A5D6FF',
    iconOk: '#56d364',
    iconCancel: 'rgb(203, 75, 22)',
  },
}

export const githubLightTheme: Theme = {
  displayName: 'Github Light',
  styles: {
    container: 'white',
    property: '#1F2328',
    bracket: '#00802e',
    itemCount: '#8B949E',
    string: '#0A3069',
    number: '#953800',
    boolean: { color: '#CF222E', fontSize: '90%', fontWeight: 'bold' },
    null: '#FF7B72',
    iconCollection: '#8250DF',
    iconEdit: '#8250DF',
    iconDelete: 'rgb(203, 75, 22)',
    iconAdd: '#8250DF',
    iconCopy: '#57606A',
  },
}

export const monoDarkTheme: Theme = {
  displayName: 'Black & White',
  fragments: {
    lightText: { color: 'white' },
    midGrey: '#5c5c5c',
  },
  styles: {
    container: ['lightText', { backgroundColor: 'black' }],
    dropZone: '#e0e0e029',
    property: 'lightText',
    bracket: 'midGrey',
    itemCount: '#4a4a4a',
    string: '#a8a8a8',
    number: '#666666',
    boolean: { color: '#848484', fontStyle: 'italic' },
    null: '#333333',
    iconCollection: 'midGrey',
    iconEdit: 'midGrey',
    iconDelete: 'midGrey',
    iconAdd: 'midGrey',
    iconCopy: 'midGrey',
    iconOk: 'midGrey',
    iconCancel: 'midGrey',
  },
}

export const monoLightTheme: Theme = {
  fragments: { midGrey: '#a3a3a3' },
  displayName: 'White & Black',
  styles: {
    container: 'white',
    property: 'black',
    bracket: 'midGrey',
    itemCount: '#b5b5b5',
    string: '#575757',
    number: '#999999',
    boolean: { color: '#7b7b7b', fontStyle: 'italic' },
    null: '#cccccc',
    iconCollection: 'midGrey',
    iconEdit: 'midGrey',
    iconDelete: 'midGrey',
    iconAdd: 'midGrey',
    iconCopy: 'midGrey',
    iconOk: 'midGrey',
    iconCancel: 'midGrey',
  },
}

export const candyWrapperTheme: Theme = {
  displayName: 'Candy Wrapper',
  fragments: {
    minty: { backgroundColor: '#F1FAEE' },
    pale: { color: '#A8DADC' },
    mid: { color: '#457B9D' },
    dark: { color: '#1D3557' },
    pop: { color: '#E63946' },
    darkBlue: { color: '#2B2D42' },
  },
  styles: {
    container: 'minty',
    property: 'pop',
    dropZone: '#eb121217',
    bracket: 'dark',
    itemCount: 'pale',
    string: 'mid',
    number: ['darkBlue', { fontSize: '85%' }],
    boolean: ['mid', { fontStyle: 'italic', fontWeight: 'bold', fontSize: '80%' }],
    null: ['#cccccc', { fontWeight: 'bold' }],
    input: { border: '1px solid rgb(115, 194, 198)' },
    iconCollection: '#1D3557',
    iconEdit: '#457B9D',
    iconDelete: '#E63946',
    iconAdd: '#2B2D42',
    iconCopy: '#1D3557',
    iconCancel: '#E63946',
  },
}

export const psychedelicTheme: Theme = {
  displayName: 'Psychedelic',
  fragments: {
    pale: { color: '#A8DADC' },
    fluroYellow: 'rgb(242, 228, 21)',
    fluroGreen: 'rgb(68, 255, 62)',
    hotPink: '#f7379a',
  },
  styles: {
    container: {
      backgroundColor: 'unset',
      background: 'linear-gradient(90deg, hsla(333, 100%, 53%, 1) 0%, hsla(33, 94%, 57%, 1) 100%)',
      color: 'black',
    },
    dropZone: 'fluroYellow',
    property: 'black',
    bracket: 'fluroYellow',
    itemCount: ['pale', { opacity: 0.7 }],
    string: 'white',
    number: ['#33d9ff', { fontSize: '90%', fontWeight: 'bold' }],
    boolean: ['fluroGreen', { fontWeight: 'bold', fontSize: '80%' }],
    null: [
      'black',
      {
        fontWeight: 'bold',
        opacity: 0.3,
        backgroundColor: 'rgb(255, 255, 255, 0.5)',
        padding: '0 0.4em',
        borderRadius: '0.4em',
      },
    ],
    iconCollection: 'fluroYellow',
    iconEdit: ['black'],
    iconDelete: ['white', { opacity: 0.5 }],
    iconAdd: ['white', { opacity: 0.5 }],
    iconCopy: 'rgb(32, 84, 242)',
    iconOk: 'fluroGreen',
    iconCancel: 'hotPink',
  },
}

export const solarizedDarkTheme: Theme = {
  displayName: 'Solarized Dark',
  fragments: {
    base03: '#002b36',
    base02: '#073642',
    base01: '#586e75',
    base0: '#839496',
    base1: '#93a1a1',
  },
  styles: {
    container: ['base0', { backgroundColor: '#002b36' }],
    dropZone: 'rgba(38, 139, 210, 0.15)',
    property: '#93a1a1',
    bracket: '#859900',
    itemCount: '#586e75',
    string: '#2aa198',
    number: { color: '#d33682', fontSize: '95%' },
    boolean: { color: '#cb4b16', fontWeight: 'bold', fontSize: '90%' },
    null: { color: '#dc322f', fontWeight: 'bold' },
    input: { border: '1px solid #586e75' },
    iconCollection: '#268bd2',
    iconEdit: '#268bd2',
    iconDelete: '#dc322f',
    iconAdd: '#859900',
    iconCopy: '#6c71c4',
    iconOk: '#859900',
    iconCancel: '#dc322f',
  },
}

export const solarizedLightTheme: Theme = {
  displayName: 'Solarized Light',
  fragments: {
    base3: '#fdf6e3',
    base2: '#eee8d5',
    base1: '#93a1a1',
    base00: '#657b83',
    base01: '#586e75',
  },
  styles: {
    container: { color: '#657b83', backgroundColor: '#fdf6e3' },
    dropZone: 'rgba(38, 139, 210, 0.15)',
    property: '#586e75',
    bracket: '#859900',
    itemCount: '#93a1a1',
    string: '#2aa198',
    number: { color: '#d33682', fontSize: '95%' },
    boolean: { color: '#cb4b16', fontWeight: 'bold', fontSize: '90%' },
    null: { color: '#dc322f', fontWeight: 'bold' },
    input: { border: '1px solid #93a1a1' },
    iconCollection: '#268bd2',
    iconEdit: '#268bd2',
    iconDelete: '#dc322f',
    iconAdd: '#859900',
    iconCopy: '#6c71c4',
    iconOk: '#859900',
    iconCancel: '#dc322f',
  },
}

export const draculaTheme: Theme = {
  displayName: 'Dracula',
  fragments: {
    background: '#282a36',
    currentLine: '#44475a',
    foreground: '#f8f8f2',
    comment: '#6272a4',
  },
  styles: {
    container: { color: '#f8f8f2', backgroundColor: '#282a36' },
    dropZone: 'rgba(139, 233, 253, 0.15)',
    property: '#f8f8f2',
    bracket: '#50fa7b',
    itemCount: '#6272a4',
    string: '#f1fa8c',
    number: { color: '#bd93f9', fontSize: '95%' },
    boolean: { color: '#ff79c6', fontWeight: 'bold', fontSize: '90%' },
    null: { color: '#ff5555', fontWeight: 'bold' },
    input: { border: '1px solid #6272a4' },
    iconCollection: '#8be9fd',
    iconEdit: '#8be9fd',
    iconDelete: '#ff5555',
    iconAdd: '#50fa7b',
    iconCopy: '#ffb86c',
    iconOk: '#50fa7b',
    iconCancel: '#ff5555',
  },
}

export const monokaiTheme: Theme = {
  displayName: 'Monokai',
  fragments: {
    background: '#272822',
    foreground: '#f8f8f2',
    comment: '#75715e',
  },
  styles: {
    container: { color: '#f8f8f2', backgroundColor: '#272822' },
    dropZone: 'rgba(166, 226, 46, 0.15)',
    property: '#a6e22e',
    bracket: '#f8f8f2',
    itemCount: '#75715e',
    string: '#e6db74',
    number: { color: '#ae81ff', fontSize: '95%' },
    boolean: { color: '#fd971f', fontWeight: 'bold', fontSize: '90%' },
    null: { color: '#f92672', fontWeight: 'bold' },
    input: { border: '1px solid #75715e' },
    iconCollection: '#66d9ef',
    iconEdit: '#66d9ef',
    iconDelete: '#f92672',
    iconAdd: '#a6e22e',
    iconCopy: '#fd971f',
    iconOk: '#a6e22e',
    iconCancel: '#f92672',
  },
}

export const tokyoNightTheme: Theme = {
  displayName: 'Tokyo Night',
  fragments: {
    background: '#1a1b26',
    foreground: '#a9b1d6',
    comment: '#565f89',
  },
  styles: {
    container: { color: '#a9b1d6', backgroundColor: '#1a1b26' },
    dropZone: 'rgba(122, 162, 247, 0.18)',
    property: '#c0caf5',
    bracket: '#7aa2f7',
    itemCount: '#565f89',
    string: '#9ece6a',
    number: { color: '#ff9e64', fontSize: '95%' },
    boolean: { color: '#f7768e', fontWeight: 'bold', fontSize: '90%' },
    null: { color: '#565f89', fontWeight: 'bold' },
    input: { border: '1px solid #565f89' },
    iconCollection: '#bb9af7',
    iconEdit: '#bb9af7',
    iconDelete: '#f7768e',
    iconAdd: '#9ece6a',
    iconCopy: '#7dcfff',
    iconOk: '#9ece6a',
    iconCancel: '#f7768e',
  },
}
