// A deep, varied org-chart document for the Filter toolkit example. It's
// deliberately broad so every builder has something to match: a top-level
// array of department records, nested teams and members, mixed value types
// (strings, numbers, booleans, nulls), URLs, ISO timestamps (`*_at` keys),
// tag/skill arrays, and both large and small collections.

export const orgData = {
  company: 'Helios Robotics',
  founded: 2009,
  public: false,
  website: 'https://heliosrobotics.example',
  employees: 184,
  headquarters: {
    city: 'Wellington',
    country: 'New Zealand',
    address: '12 Cuba Street',
    geo: { lat: -41.2924, lng: 174.7787 },
  },
  parentCompany: null,
  certifications: ['ISO 9001', 'ISO 27001', 'B-Corp'],
  created_at: '2009-03-14T09:00:00Z',
  updated_at: '2026-06-10T16:45:00Z',
  departments: [
    {
      id: 'dept-eng',
      name: 'Engineering',
      headcount: 64,
      budget: 4200000,
      remote: true,
      lead: {
        name: 'Ada Okonkwo',
        email: 'ada@heliosrobotics.example',
        phone: '+64 21 555 0101',
      },
      tags: ['firmware', 'control-systems', 'simulation'],
      teams: [
        {
          name: 'Motion Control',
          focus: 'Actuator firmware and real-time control loops',
          active: true,
          repository: 'https://git.example/helios/motion',
          members: [
            {
              id: 'u-1042',
              name: 'Bao Tran',
              email: 'bao@heliosrobotics.example',
              role: 'Staff Engineer',
              active: true,
              skills: ['C++', 'RTOS', 'Kalman filters'],
              joined: '2014-08-01',
              avatar: 'https://cdn.example/avatars/bao.png',
              manager: null,
              created_at: '2014-08-01T08:30:00Z',
            },
            {
              id: 'u-1108',
              name: 'Priya Nair',
              email: 'priya@heliosrobotics.example',
              role: 'Senior Engineer',
              active: true,
              skills: ['Rust', 'embedded Linux'],
              joined: '2018-02-12',
              avatar: 'https://cdn.example/avatars/priya.png',
              manager: 'u-1042',
              created_at: '2018-02-12T10:00:00Z',
            },
          ],
        },
        {
          name: 'Perception',
          focus: 'Sensor fusion and computer vision',
          active: true,
          repository: 'https://git.example/helios/perception',
          members: [
            {
              id: 'u-1190',
              name: 'Marcus Webb',
              email: 'marcus@heliosrobotics.example',
              role: 'Engineer',
              active: false,
              skills: ['Python', 'PyTorch', 'OpenCV', 'SLAM'],
              joined: '2020-09-30',
              avatar: 'https://cdn.example/avatars/marcus.png',
              manager: 'u-1042',
              created_at: '2020-09-30T14:15:00Z',
            },
          ],
        },
      ],
    },
    {
      id: 'dept-design',
      name: 'Design',
      headcount: 18,
      budget: 980000,
      remote: false,
      lead: {
        name: 'Sofia Marchetti',
        email: 'sofia@heliosrobotics.example',
        phone: '+64 21 555 0144',
      },
      tags: ['industrial-design', 'ux'],
      teams: [
        {
          name: 'Hardware Design',
          focus: 'Enclosures, ergonomics and materials',
          active: true,
          repository: null,
          members: [
            {
              id: 'u-2051',
              name: 'Tomas Beck',
              email: 'tomas@heliosrobotics.example',
              role: 'Industrial Designer',
              active: true,
              skills: ['CAD', 'prototyping'],
              joined: '2016-05-04',
              avatar: 'https://cdn.example/avatars/tomas.png',
              manager: null,
              created_at: '2016-05-04T09:45:00Z',
            },
            {
              id: 'u-2099',
              name: 'Lena Ford',
              email: 'lena@heliosrobotics.example',
              role: 'UX Designer',
              active: true,
              skills: ['Figma', 'user-research', 'prototyping'],
              joined: '2021-11-22',
              avatar: 'https://cdn.example/avatars/lena.png',
              manager: 'u-2051',
              created_at: '2021-11-22T11:30:00Z',
            },
          ],
        },
      ],
    },
    {
      id: 'dept-ops',
      name: 'Field Operations',
      headcount: 41,
      budget: 1750000,
      remote: false,
      lead: {
        name: 'Diego Alvarez',
        email: 'diego@heliosrobotics.example',
        phone: '+64 21 555 0177',
      },
      tags: ['deployment', 'support', 'logistics'],
      teams: [
        {
          name: 'Deployment',
          focus: 'On-site installation and commissioning',
          active: true,
          repository: 'https://git.example/helios/deploy-runbooks',
          members: [
            {
              id: 'u-3010',
              name: 'Hana Suzuki',
              email: 'hana@heliosrobotics.example',
              role: 'Field Engineer',
              active: true,
              skills: ['networking', 'PLC', 'safety-systems'],
              joined: '2019-07-08',
              avatar: 'https://cdn.example/avatars/hana.png',
              manager: null,
              created_at: '2019-07-08T08:00:00Z',
            },
          ],
        },
        {
          name: 'Support',
          focus: 'Customer support and incident response',
          active: false,
          repository: null,
          members: [
            {
              id: 'u-3088',
              name: 'Omar Haddad',
              email: 'omar@heliosrobotics.example',
              role: 'Support Lead',
              active: true,
              skills: ['troubleshooting', 'documentation'],
              joined: '2022-03-15',
              avatar: 'https://cdn.example/avatars/omar.png',
              manager: 'u-3010',
              created_at: '2022-03-15T13:20:00Z',
            },
          ],
        },
      ],
    },
  ],
}
