import { type CompiledStyles, type DefaultTheme } from '../types'

export const defaultTheme: DefaultTheme = {
  displayName: 'Default',
  fragments: { edit: 'rgb(42, 161, 152)' },
  styles: {
    container: {
      backgroundColor: '#f6f6f6',
      fontFamily: 'monospace',
    },
    collection: {},
    collectionInner: {},
    collectionElement: {},
    dropZone: {},
    property: '#292929',
    bracket: { color: 'rgb(0, 43, 54)', fontWeight: 'bold' },
    itemCount: { color: 'rgba(0, 0, 0, 0.3)', fontStyle: 'italic' },
    string: 'rgb(203, 75, 22)',
    number: 'rgb(38, 139, 210)',
    boolean: 'green',
    null: { color: 'rgb(220, 50, 47)', fontVariant: 'small-caps', fontWeight: 'bold' },
    input: ['#292929'],
    inputHighlight: '#b3d8ff',
    error: { fontSize: '0.8em', color: 'red', fontWeight: 'bold' },
    iconCollection: 'rgb(0, 43, 54)',
    iconEdit: 'edit',
    iconDelete: 'rgb(203, 75, 22)',
    iconAdd: 'edit',
    iconCopy: 'rgb(38, 139, 210)',
    iconOk: 'green',
    iconCancel: 'rgb(203, 75, 22)',
  },
}

export const emptyStyleObject: CompiledStyles = {
  container: {},
  collection: {},
  collectionInner: {},
  collectionElement: {},
  dropZone: {},
  property: {},
  bracket: {},
  itemCount: {},
  string: {},
  number: {},
  boolean: {},
  null: {},
  input: {},
  inputHighlight: {},
  error: {},
  iconCollection: {},
  iconEdit: {},
  iconDelete: {},
  iconAdd: {},
  iconCopy: {},
  iconOk: {},
  iconCancel: {},
}
