export const initialData = [
  {
    name: 'Steve Rogers',
    dateOfBirth: '1920-07-04T12:00:00-05:00',
    aliases: ['Captain America', 'The First Avenger'],
    logo: 'https://logos-world.net/wp-content/uploads/2023/05/Captain-America-Logo.png',
    portrayedBy: ['Chris Evans'],
    publisher: 'Marvel',
  },
  {
    name: 'Peter Parker',
    dateOfBirth: '2001-08-09T16:30:00.000Z',
    aliases: ['Spiderman'],
    logo: 'https://logos-world.net/wp-content/uploads/2020/11/Spider-Man-Logo.png',
    portrayedBy: ['Tobey Maguire', 'Andrew Garfield', 'Tom Holland'],
    publisher: 'Marvel',
  },
  {
    name: 'Clark Kent',
    dateOfBirth: '1977-04-14T12:00:00-06:00',
    aliases: ['Superman', 'Man of Steel', 'Son of Krypton'],
    logo: 'https://logos-world.net/wp-content/uploads/2020/11/Superman-Logo.png',
    portrayedBy: ['Christopher Reeve', 'Brandon Routh', 'Henry Cavill'],
    publisher: 'D.C. Comics',
  },
  {
    name: 'Bruce Wayne',
    dateOfBirth: '1970-02-18T18:00:00.000Z',
    aliases: ['Batman', 'The Dark Knight', 'The Caped Crusader'],
    logo: 'https://logos-world.net/wp-content/uploads/2020/12/Batman-Logo.png',
    portrayedBy: [
      'Michael Keaton',
      'George Clooney',
      'Val Kilmer',
      'Christian Bale',
      'Ben Affleck',
      'Robert Pattinson',
    ],
    publisher: 'D.C. Comics',
  },
]
