const defaultTheme = {
  name: 'Default',
  bgColor: '#f6f6f6',
  borderColor: 'rgb(0, 0, 0, 0.2)',
  mainFont: 'monospace',
  mainFontColor: '#292929',
  bracketColor: 'rgb(0, 43, 54)',
  parentheticalColor: 'rgba(0, 0, 0, 0.3)',
  stringColor: 'rgb(203, 75, 22)',
  numberColor: 'rgb(38, 139, 210)',
  booleanColor: 'green',
  nullColor: 'rgb(220, 50, 47)',
  inputColor: '#292929',
  highlightColor: '#b3d8ff',
  iconChevronColor: 'rgb(0, 43, 54)',
  iconEditColor: 'rgb(42, 161, 152)',
  iconDeleteColor: 'rgb(203, 75, 22)',
  iconAddColor: 'rgb(42, 161, 152)',
  iconCopyColor: 'rgb(38, 139, 210)',
  iconOkColor: 'green',
  iconCancelColor: 'rgb(203, 75, 22)',
}

export type ThemeProps = typeof defaultTheme
export type ThemePropName = keyof Omit<ThemeProps, 'name'>
export type ThemeName = keyof typeof themes

export const themes = {
  default: defaultTheme,
  githubDark: {
    name: 'Github Dark',
    bgColor: '#0d1117',
    borderColor: 'transparent',
    mainFont: 'monospace',
    mainFontColor: '#E6EDF3',
    bracketColor: '#56d364',
    parentheticalColor: '#8B949E',
    stringColor: '#A5D6FF',
    numberColor: '#D2A8FF',
    booleanColor: '#FF7B72',
    nullColor: '#FF7B72',
    inputColor: '#292929',
    highlightColor: '#b3d8ff',
    iconChevronColor: '#D2A8FF',
    iconEditColor: '#D2A8FF',
    iconDeleteColor: 'rgb(203, 75, 22)',
    iconAddColor: '#D2A8FF',
    iconCopyColor: '#A5D6FF',
    iconOkColor: '#56d364',
    iconCancelColor: 'rgb(203, 75, 22)',
  },
  githubLight: {
    name: 'Github Light',
    bgColor: 'white',
    borderColor: 'transparent',
    mainFont: 'monospace',
    mainFontColor: '#1F2328',
    bracketColor: '#00802e',
    parentheticalColor: '#8B949E',
    stringColor: '#0A3069',
    numberColor: '#953800',
    booleanColor: '#CF222E',
    nullColor: '#FF7B72',
    inputColor: '#292929',
    highlightColor: '#b3d8ff',
    iconChevronColor: '#8250DF',
    iconEditColor: '#8250DF',
    iconDeleteColor: 'rgb(203, 75, 22)',
    iconAddColor: '#8250DF',
    iconCopyColor: '#57606A',
    iconOkColor: 'green',
    iconCancelColor: 'rgb(203, 75, 22)',
  },
  monoDark: {
    name: 'Black & White',
    bgColor: 'black',
    borderColor: 'transparent',
    mainFont: 'monospace',
    mainFontColor: 'white',
    bracketColor: '#5c5c5c',
    parentheticalColor: '#4a4a4a',
    stringColor: '#a8a8a8',
    numberColor: '#666666',
    booleanColor: '#848484',
    nullColor: '#333333',
    inputColor: '#292929',
    highlightColor: '#b3d8ff',
    iconChevronColor: '#5c5c5c',
    iconEditColor: '#5c5c5c',
    iconDeleteColor: '#5c5c5c',
    iconAddColor: '#5c5c5c',
    iconCopyColor: '#5c5c5c',
    iconOkColor: '#5c5c5c',
    iconCancelColor: '#5c5c5c',
  },
  monoLight: {
    name: 'White & Black',
    bgColor: 'white',
    borderColor: 'transparent',
    mainFont: 'monospace',
    mainFontColor: 'black',
    bracketColor: '#a3a3a3',
    parentheticalColor: '#b5b5b5',
    stringColor: '#575757',
    numberColor: '#999999',
    booleanColor: '#7b7b7b',
    nullColor: '#cccccc',
    inputColor: '#292929',
    highlightColor: '#b3d8ff',
    iconChevronColor: '#a3a3a3',
    iconEditColor: '#a3a3a3',
    iconDeleteColor: '#a3a3a3',
    iconAddColor: '#a3a3a3',
    iconCopyColor: '#a3a3a3',
    iconOkColor: '#a3a3a3',
    iconCancelColor: '#a3a3a3',
  },
} as const satisfies Record<string, ThemeProps>

const ob = {
  name: 'string',
  number: 666,
  boolean: false,
  null: null,
  array: [1, 2, 3, 4],
  obj: { one: 1 },
}
